dist: xenial
language: python
python:
  - '3.7'
stages:
  - build
  - static-checks
  - test
jobs:
  include:
    - stage: build
      script:
        - pip install --upgrade pip
        - python setup.py install
    - stage: static-checks
      script:
        - flake8 .
        - black . --check
        # mode 3 with trailing commas is black compatible isort
        # turning off because it passes locally and fails in ci!?
        # - isort -m 3 -tc -c buzz/* tests/* setup.py
    - stage: test
      script:
        - pip install --upgrade pip
        - python setup.py install
        - coverage run -m unittest
        - codecov
